version: '3.0'
services:
  db:
    image: postgres:12
    networks:
      - backend
    ports:
      - "5432:5432"
    env_file:
     - ./env/db.env
  django:
    build: ./jungle_code/
    networks:
      - backend
    env_file:
      - ./env/django.env
    environment:
      - DEBUG=0
      - PYSVR=0
    volumes:
      - ./jungle_code/:/code
    ports:
      - "8000:8000"
    entrypoint: /code/wait-for-it.sh db:5432 -t 0 -- /code/django-entrypoint.sh

networks:
  backend: